<a href="https://colab.research.google.com/github/BelajarMachineLearning/Pengenalan-Deep-Learning/blob/main/2_Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Element Wise Operations


In [ ]:
# create tensor
from numpy import array
import numpy as np

T1 = array([[1,2,3],    [4,5,6]])
T2 = array([[2,4,6],    [8,10,6]])

print(T1)
print(T2)


[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10  6]]


In [ ]:
print(T1.shape)
print(T2.shape)

(2, 3)
(2, 3)


In [ ]:
T1 + T2

array([[ 3,  6,  9],
       [12, 15, 12]])

In [ ]:
T1 * T2

array([[ 2,  8, 18],
       [32, 50, 36]])

Broadcasting

In [ ]:
 T1 + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.broadcast_to(2, T1.shape)


array([[2, 2, 2],
       [2, 2, 2]])

In [ ]:
T1 + np.broadcast_to(2, T1.shape)

array([[3, 4, 5],
       [6, 7, 8]])

Tensor Dot

In [ ]:
T2.shape
np.dot(T1, T2)

ValueError: ignored

In [ ]:
T3 = np.transpose(T2)

T3.shape

(3, 2)

In [ ]:
print(T1)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(T3)

[[ 2  8]
 [ 4 10]
 [ 6  6]]


In [ ]:
np.dot(T1,T3)

array([[ 28,  46],
       [ 64, 118]])

Tensor re-shaping

In [ ]:
T1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
T1.shape

(2, 3)

In [ ]:
T1.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])